// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_dbmanager.cpp"
#include "EWIEGA46WW/moc_newobject.cpp"
#include "EWIEGA46WW/moc_sort.cpp"
#include "EWIEGA46WW/moc_widget.cpp"
